name: adv
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10.10
  - pytorch 
  - torchvision 
  - torchaudio 
  - pytorch-cuda=11.8
  - cupy 
  - pkg-config 
  - libjpeg-turbo 
  - opencv 
  - numba 
  - cudatoolkit 
  - cudnn 
  - matplotlib 
  - scipy=1.7.3
  - jupyterlab
  - pip
  - matplotlib
  - tqdm
  - pip:
      - install 
      - ffcv 
      - composer 
      - torchattacks==3.2.7